[package]
name = "sparx"
version = "1.0.0"
edition = "2021"
authors = ["Tim Stuart <stuartt@gis.a-star.edu.sg>"]
description = "💥 Disk-based sparse matrix statistics and subsetting 💥"
license = "MIT"
repository = "https://github.com/stuart-lab/sparx"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
flate2 = "1.0"
regex = "1.5"
rand = "0.8"
nalgebra = "0.33"